[tool.poetry]
name = "aoc-py"
version = "0.1.0"
description = ""
authors = ["Volodymyr Anokhin <vlnn-github@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
